"""
Technical Writer Agent implementation.
"""
from datetime import datetime, timezone
from pathlib import Path
from workflow.config import CONTENT_DIR
from workflow.agents.base_agent import BaseAgent, AgentResult

class TechnicalWriter(BaseAgent):
    """Agent responsible for writing Hugo markdown drafts and page bundles."""
    
    def __init__(self):
        super().__init__(name="Technical Writer", role="Hugo Markdown & Frontmatter Author")

    def slugify(self, text: str) -> str:
        return text.lower().strip().replace(" ", "-").replace("_", "-")

    def run(self, brief: dict) -> AgentResult:
        topic = brief.get("topic", "Untitled Post")
        slug = self.slugify(brief.get("suggested_slug", topic))
        tags = brief.get("recommended_tags", ["Engineering"])
        
        post_dir = CONTENT_DIR / slug
        post_dir.mkdir(parents=True, exist_ok=True)
        index_file = post_dir / "index.md"
        
        self.log(f"Scaffolding page bundle at: {post_dir}", "cyan")
        
        now_str = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S+00:00")
        tags_str = ", ".join([f'"{t}"' for t in tags])
        
        content = f"""---
title: "{topic}"
date: {now_str}
author: "Vikas Phatak"
description: "A technical deep-dive and tutorial covering {topic} for modern software engineers."
tags: [{tags_str}]
categories: ["Engineering", "AI Systems"]
draft: true
ShowToc: true
---

## Introduction to {topic}

This draft was generated by the **Technical Writer Agent** following a structured research brief.

### Key Takeaways
"""
        for pt in brief.get("key_takeaways", []):
            content += f"- {pt}\n"
            
        content += """
### Code Example & Verification

```python
# /// script
# dependencies = ["rich"]
# ///
from rich import print

print("[bold cyan]Hello from an ephemeral uv sandbox![/bold cyan]")
```

## Conclusion

Summary and next steps.
"""
        index_file.write_text(content, encoding="utf-8")
        self.log(f"Draft written to: {index_file}", "bold green")
        
        return AgentResult(
            agent_name=self.name,
            success=True,
            output={"post_dir": str(post_dir), "index_file": str(index_file), "slug": slug}
        )
