"""
Git Publisher module for managing branches, build verification, commits, and Pull Requests.
"""
import subprocess
import re
from pathlib import Path
from typing import Optional
from rich.console import Console

from workflow.config import CONFIG, ROOT_DIR
from workflow.agents.base_agent import BaseAgent, AgentResult

console = Console()

class GitPublisher(BaseAgent):
    """Agent responsible for Git version control and GitHub PR publication."""
    
    def __init__(self):
        super().__init__(name="Git Publisher", role="Git & Static Site Ops")

    def _run_cmd(self, cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
        """Run a shell command inside the repository root."""
        return subprocess.run(
            cmd,
            cwd=ROOT_DIR,
            capture_output=True,
            text=True,
            check=check
        )

    def verify_hugo_build(self) -> bool:
        """Run local Hugo pre-flight check."""
        self.log("Running local Hugo build check: hugo --minify --panicOnWarning", "yellow")
        try:
            res = self._run_cmd(["hugo", "--minify", "--panicOnWarning"], check=False)
            if res.returncode != 0:
                self.log(f"Hugo build check FAILED!\n{res.stderr}", "bold red")
                return False
            self.log("Hugo pre-flight check PASSED cleanly!", "bold green")
            return True
        except Exception as e:
            self.log(f"Error executing Hugo: {str(e)}", "bold red")
            return False

    def slugify(self, text: str) -> str:
        """Convert a title into a clean git branch slug."""
        text = text.lower().strip()
        text = re.sub(r'[^\w\s-]', '', text)
        return re.sub(r'[\s_-]+', '-', text)

    def run(self, post_dir: Path, title: str, auto_pr: bool = False) -> AgentResult:
        """Execute git branch creation, commit, and PR generation."""
        self.log(f"Initiating Git publishing sequence for: {post_dir}", "cyan")
        
        # 1. Pre-flight Hugo check
        if not self.verify_hugo_build():
            return AgentResult(
                agent_name=self.name,
                success=False,
                output="Hugo build check failed.",
                errors=["Pre-flight hugo --minify --panicOnWarning failed."]
            )

        slug = self.slugify(title)
        branch_name = f"post/{slug}"
        
        try:
            # 2. Check if branch exists or create new
            self.log(f"Creating/checking out feature branch: [bold]{branch_name}[/bold]", "yellow")
            self._run_cmd(["git", "checkout", "-b", branch_name], check=False)
            
            # 3. Stage the post directory
            rel_path = post_dir.relative_to(ROOT_DIR)
            self.log(f"Staging content: {rel_path}", "yellow")
            self._run_cmd(["git", "add", str(rel_path)])
            
            # 4. Commit changes
            commit_msg = f"feat(content): publish post on {title}"
            self.log(f"Committing with message: '{commit_msg}'", "yellow")
            self._run_cmd(["git", "commit", "-m", commit_msg], check=False)
            
            pr_url = None
            if auto_pr:
                # 5. Push and open PR
                self.log(f"Pushing branch {branch_name} to origin...", "yellow")
                self._run_cmd(["git", "push", "-u", "origin", branch_name])
                
                self.log("Opening GitHub Pull Request via gh CLI...", "yellow")
                pr_res = self._run_cmd([
                    "gh", "pr", "create",
                    "--title", f"feat(content): {title}",
                    "--body", "Automated PR generated by AGY Editorial Pipeline.\n\n- [x] Hugo build verification passed.\n- [x] SEO & Quality gates checked.",
                    "--base", CONFIG.default_branch
                ], check=False)
                
                if pr_res.returncode == 0:
                    pr_url = pr_res.stdout.strip()
                    self.log(f"Pull Request created: {pr_url}", "bold green")
                else:
                    self.log(f"PR creation warning: {pr_res.stderr}", "yellow")
            
            return AgentResult(
                agent_name=self.name,
                success=True,
                output={"branch": branch_name, "commit_msg": commit_msg, "pr_url": pr_url},
                metadata={"post_dir": str(rel_path)}
            )
            
        except Exception as e:
            self.log(f"Git operation failed: {str(e)}", "bold red")
            return AgentResult(
                agent_name=self.name,
                success=False,
                output="Git operations encountered an error.",
                errors=[str(e)]
            )
